---
- name: Activate ES trial license (with security authentication)
  ansible.builtin.uri:
    method: POST
    url: "{{ es_api_uri }}/{{ es_license_api }}/start_trial?acknowledge=true"
    user: "{{ es_api_basic_auth_username | default(omit) }}"
    password: "{{ es_api_basic_auth_password | default(omit) }}"
    return_content: true
    force_basic_auth: true
    status_code:
      - 200
      - 403
    validate_certs: "{{ es_validate_certs }}"
  register: trial_license_activated
  when: es_xpack_trial

- name: Trial license
  ansible.builtin.debug:
    msg: "{{ trial_license_activated }}"
